---
title: "Reproducible Research: Peer Assessment 1"
output:   html_document
    keep_md: true
---


## Loading and preprocessing the data
Reading and preprocessing data  
```{r, echo=TRUE}
myData <- read.csv("activity.csv")
cleanData <- myData[complete.cases(myData),]
cleanData$date <- as.Date(cleanData$date)

```

## What is mean total number of steps taken per day?

Histogram of Steps per day:
```{r}

perDay <- aggregate(cleanData$steps,by=list(cleanData$date),FUN=sum)
colnames(perDay) <- c("day","totalSteps")
hist(perDay$totalSteps,main="Steps per day", xlab="Total Steps")
```
Mean: 
```{r}
mean(perDay$totalSteps)
```

Meadian: 
```{r}
median(perDay$totalSteps)
```

## What is the average daily activity pattern?
Average daily activity pattern
 
```{r}
perInterval <- aggregate(cleanData$steps, by = list(cleanData$interval), FUN=mean)
colnames(perInterval)<- c("interval","avgSteps")

plot(perInterval$interval,perInterval$avgSteps,type="l",xlab = "Interval", ylab="Average Steps Taken")

indx <- which(perInterval$avgSteps==max(perInterval$avgSteps))
highest <- perInterval[indx,1]
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?



